# Generated by Django 3.2.5 on 2021-07-09 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210707_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_ending', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='question',
            name='date_ending',
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.poll'),
        ),
    ]
