# Generated by Django 3.2.5 on 2021-07-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210709_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Choice', 'Choice'), ('MultipleChoice', 'MultipleChoice'), ('UserText', 'UserText')], default='Choice', max_length=14),
        ),
    ]
