# Generated by Django 3.2.5 on 2021-07-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='anser',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
